class HomeConstants {
  static const List<String> motivationalQuotes = [
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Successful and unsuccessful people do not vary greatly in their abilities. They vary in their desires to reach their potential. - John Maxwell",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. - Jim Rohn",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "Successful people are not gifted; they just work hard, then succeed on purpose. - G.K. Nielson",
    "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Successful people maintain a positive focus in life no matter what is going on around them. They stay focused on their past successes rather than their past failures, and on the next action steps they need to take to get them closer to the fulfillment of their goals rather than all the other distractions that life presents to them. - Jack Canfield",
    "The difference between ordinary and extraordinary is that little extra. - Jimmy Johnson",
    "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
    "Success is not how much money you make, but the difference you make in people's lives. - Michelle Obama",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The secret of success is to do the common things uncommonly well. - John D. Rockefeller Jr.",
    "You can't build a reputation on what you are going to do. - Henry Ford",
    "Successful people are not afraid of failure. Instead, they use failure as a stepping stone to success. - Unknown",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Success is the result of perfection, hard work, learning from failure, loyalty, and persistence. - Colin Powell",
    "Successful people are not gifted; they just work hard, then succeed on purpose. - G.K. Nielson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand. - Vince Lombardi",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Success is a journey, not a destination. The doing is often more important than the outcome. - Arthur Ashe",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success is not a good teacher, failure makes you humble. - Shah Rukh Khan",
    "Success is not determined by the outcome, but by the journey. It's about making an effort, trying your best, and being proud of what you have accomplished. - Unknown",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Success is the result of our own determination, hard work, and perseverance. - Unknown",
    "Success is not about how much money you make, but about the difference you make in people's lives. - Michelle Obama",
    "Successful people are action-oriented and they have a strong desire to achieve their goals. They believe in themselves and their abilities, and they are not afraid to take risks to get what they want. - Jack Canfield",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Success is not the absence of failure; it's the persistence through failure. - Aisha Tyler",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Success is not determined by the outcome, but by the journey. It's about making an effort, trying your best, and being proud of what you have accomplished. - Unknown",
    "Success is not a destination, it's a journey. Enjoy the ride and celebrate every step of the way. - Unknown",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer"
  ];
}
